name: CD

on:
  release:
    types: [published]

jobs:

  setup:
    name: Setup environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: pip install 'gdown<6.0.0'

      - name: Download raw dataset
        run: gdown --fuzzy "$GOOGLE_DRIVE_LINK" -O raw-dataset.tar
        env:
          GOOGLE_DRIVE_LINK: ${{ secrets.GOOGLE_DRIVE_LINK }}

      - name: Encrypt raw dataset
        run: openssl enc -aes-256-cbc -pbkdf2 -in raw-dataset.tar -out raw-dataset.tar.enc -pass env:ARTIFACT_KEY
        env:
          ARTIFACT_KEY: ${{ secrets.ARTIFACT_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: raw-dataset
          path: raw-dataset.tar.enc
          retention-days: 1

  preprocess:
    name: Preprocess data
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: raw-dataset

      - name: Decrypt and unpack raw dataset
        run: |
          openssl enc -d -aes-256-cbc -pbkdf2 -in raw-dataset.tar.enc -out raw-dataset.tar -pass env:ARTIFACT_KEY
          mkdir -p _data
          tar -xf raw-dataset.tar -C _data
        env:
          ARTIFACT_KEY: ${{ secrets.ARTIFACT_KEY }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - name: Preprocess and encrypt training data
        run: |
          make -j 10
          openssl enc -aes-256-cbc -pbkdf2 -in dataset.tar.gz -out dataset.tar.gz.enc -pass env:ARTIFACT_KEY
        env:
          ARTIFACT_KEY: ${{ secrets.ARTIFACT_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: dataset.tar.gz.enc
          retention-days: 1

  upload:
    name: Upload model
    runs-on: ubuntu-latest
    needs: preprocess

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: preprocessed-dataset

      - name: Decrypt preprocessed dataset
        run: |
          openssl enc -d -aes-256-cbc -pbkdf2 -in dataset.tar.gz.enc -out dataset.tar.gz -pass env:ARTIFACT_KEY
        env:
          ARTIFACT_KEY: ${{ secrets.ARTIFACT_KEY }}

      - run: pip install huggingface_hub

      - run: python3 upload.py
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
