name: CI

on:
  push:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up uv
        uses: astral-sh/setup-uv@v5

      - name: install dependencies
        run: |
          uv pip install --system flake8 "black[jupyter]" isort

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

  test:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up the environment
        run: ./setup.sh
        env:
          PROFILES_V1_GDRIVE: ${{ secrets.PROFILES_V1_GDRIVE }}
          CA_V1_GDRIVE: ${{ secrets.CA_V1_GDRIVE }}

      - name: build dataset and examples
        run: HEAVYEDGE_TEST_MODE=1 make

      - uses: actions/upload-artifact@v4
        with:
          name: raw-dataset
          path: _data/v1/profiles/dataset1/001-*
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: datasets/v1/profiles/dataset1/001-*

  find-notebooks:

      runs-on: ubuntu-latest

      outputs:
        notebooks: ${{ steps.list.outputs.notebooks }}

      steps:

        - name: get repo
          uses: actions/checkout@v3

        - name: list notebooks
          id: list
          run: |
            notebooks=$(find examples -name "*.ipynb" | sort | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "notebooks=$notebooks" >> $GITHUB_OUTPUT

  build-notebooks:

      needs: find-notebooks

      runs-on: ubuntu-latest

      strategy:
        fail-fast: false
        matrix:
          notebook: ${{ fromJson(needs.find-notebooks.outputs.notebooks) }}

      steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up the environment
        run: ./setup.sh && uv pip install --system -r examples/requirements.txt
        env:
          PROFILES_V1_GDRIVE: ${{ secrets.PROFILES_V1_GDRIVE }}
          CA_V1_GDRIVE: ${{ secrets.CA_V1_GDRIVE }}

      - run: make ${{ matrix.notebook }}

  image-dev:

    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: raw-dataset
          path: _data/v1/profiles/dataset1

      - uses: actions/download-artifact@v4
        with:
          name: preprocessed-dataset
          path: datasets/v1/profiles/dataset1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: dev
          cache-from: type=gha,scope=profile-dataset-dev
          cache-to: type=gha,mode=max,scope=profile-dataset-dev
          tags: heavyedge-profile-dataset:dev-ci

      - name: Test Docker image
        run: |
            docker run --rm heavyedge-profile-dataset:dev-ci sh -c 'uv pip install --system -r requirements.txt -r examples/requirements.txt && HEAVYEDGE_TEST_MODE=1 make'
