name: CI

on:
  push:
  pull_request:

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up uv
        uses: astral-sh/setup-uv@v5

      - name: install dependencies
        run: |
          uv pip install --system flake8 black isort

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

      - name: lint with isort
        run: |
          isort --check .

  test:

    runs-on: ubuntu-latest

    steps:

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: set up the environment
        run: ./setup.sh
        env:
          PROFILES_V1_GDRIVE: ${{ secrets.PROFILES_V1_GDRIVE }}

      - name: test
        run: make test

  image-dev:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          push: false
          target: dev
          cache-from: type=gha,scope=profile-dataset-dev
          cache-to: type=gha,mode=max,scope=profile-dataset-dev
          tags: heavyedge-profile-dataset:dev-ci

      - name: Test Docker image
        run: |
          docker run --rm -e PROFILES_V1_GDRIVE heavyedge-profile-dataset:dev-ci sh -c './setup.sh && make test'
        env:
          PROFILES_V1_GDRIVE: ${{ secrets.PROFILES_V1_GDRIVE }}
